context:
  version: "3.0.5"
  python_min: "3.11"

package:
  name: apify-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/apify-client/apify_client-${{ version }}.tar.gz
  sha256: 29b8066fb4327eb88bd5f3022d7c4aa2f8aed747da77a77ad6216a939620bf60

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - colorama >=0.4.0
    - impit >=0.13.0,<0.14.0
    - more-itertools >=10.0.0
    - pydantic >=2.11.0
    - email-validator

tests:
  - python:
      imports:
        - apify_client
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://docs.apify.com/api/client/python/
  summary: Apify API client for Python
  description: |
    The Apify API client for Python is the official library to access the
    Apify REST API from your Python applications. It provides useful features
    like automatic retries and convenience functions that improve the Apify
    platform experience.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://docs.apify.com/api/client/python/
  repository: https://github.com/apify/apify-client-python

extra:
  recipe-maintainers:
    - Pijukatel
